### ISSUE TITLE
Error in Kalman Filter?

### ISSUE THREAD

**Issue by ooaj** [DanielMartensson/CControl#2]
https://github.com/DanielMartensson/CControl/blob/master/src/CControl/Sources/ControlEngineering/kalman.c

Please consider the x as given in line 12 as
```
 * x = Ax - KCx + Bu + Ky 
 ```
the ```-KCx``` term should be in terms of predicted ```x```. e.g. ```-KC(Ax + Bu)```

**Comment by DanielMartensson** [comment]
> https://github.com/DanielMartensson/CControl/blob/master/src/CControl/Sources/ControlEngineering/kalman.c
> 
> Please consider the x as given in line 12 as
> 
> ```
>  * x = Ax - KCx + Bu + Ky 
> ```
> 
> the `-KCx` term should be in terms of predicted `x`. e.g. `-KC(Ax + Bu)`

Why does I never see notifications?

Anyway, state update can be written like this:
```
x = x + K(difference)
```
If we say that `difference = ymeasurement - yhat= y - Cx` and next state update is `x = Ax + Bu`. Then we can write the observer like this:

```
dx = Ax + Bu + K(y - Cx)
```
This is the same way as writing as this:

```
dx = (A - KC)x + Bu + Ky
```

And it's the same way for simplification:
```
dx = Ax - KCx + Bu + Ky
```

By the way. I recommend Unscented Kalman Filter every day over a linear Kalman Filter. The linear Kalman Filter works good, but Unscented Kalman Filter works even better for all systems. 

If you don't know the models of your system and you only want to filter it. Then you can use a random gaussian variable instead. See STM32-Libraries repository -> VLX6180 laser sensor measurement.
