### ISSUE TITLE
Possible invalid memory access?

### ISSUE THREAD

**Issue by yangzq50** [DanielMartensson/CControl#20]
https://github.com/DanielMartensson/CControl/blob/968d17ed428732de5bb01f104dd09b7497a06ef2/src/CControl/Sources/LinearAlgebra/svd.c#L690-L698

Is it possible that when ` m = 0 ` ,  ` diagonal[m - 1] ` will access invalid memory address?
Or is this circumstance prevented by the algorithm?

**Comment by DanielMartensson** [comment]
Thank you @yangzq50 

Can you run som examples and see if m is going to be 0?
