### ISSUE TITLE
Usage of svd_jacobi_one_sided

### ISSUE THREAD

**Issue by yangzq50** [DanielMartensson/CControl#21]
https://github.com/DanielMartensson/CControl/blob/968d17ed428732de5bb01f104dd09b7497a06ef2/src/CControl/Sources/LinearAlgebra/svd.c#L230

This function ` svd_jacobi_one_sided `  seems simple, and I want to use it as a header-only third-party library in an open source project.
I am curious that, does this function only accept symmetric square matrix? Or does it also accept non-symmetric square matrix?
Given that in the following function ` svd ` , ` svd_jacobi_one_sided ` is used only when the input matrix is a symmetric square matrix.

https://github.com/DanielMartensson/CControl/blob/968d17ed428732de5bb01f104dd09b7497a06ef2/src/CControl/Sources/LinearAlgebra/svd.c#L208-L213

**Comment by DanielMartensson** [comment]
Hi @yangzq50 

Jacobi one sided is only for symmetrical matrices. Jacobi is much faster to compute.

It's very common that in practice, you ending up with symmetrical matrices.

Golub and reinsch is a more time consuming algorithm, very useful when your data matrix ending up as non symmetrical. There are some cases when that happens.
