### ISSUE TITLE
Known invalid memory access

### ISSUE THREAD

**Issue by yangzq50** [DanielMartensson/CControl#22]
https://github.com/DanielMartensson/CControl/blob/968d17ed428732de5bb01f104dd09b7497a06ef2/src/CControl/Sources/LinearAlgebra/svd.c#L538-L543
Observe that, after the for loop, pointer pu points to U[nrows * ncols].
Do you have any clue?

**Comment by DanielMartensson** [comment]
@yangzq50 can you show me an example ?
