### ISSUE TITLE
Support for Complex Matrix Eigenvalue Decomposition (like cgeev or zgeev)?

### ISSUE THREAD

**Issue by Joeyue68** [DanielMartensson/CControl#23]
Hi ,

Thank you for your amazing work on this project!

I have a question regarding eigenvalue decomposition functionality. Specifically, does this project support complex matrix eigenvalue decomposition, similar to LAPACK’s cgeev or zgeev functions?

Any guidance or suggestions would be greatly appreciated. Thank you for your time!

Best regards

**Comment by DanielMartensson** [comment]
@Joeyue68 

Hi!
CControl only supports real numbers.

But if you want to implement it, it's very easy. 

MKL have some examples how to do. I have never used complex numbers in reality. I think  complex numbers are more into research fields.
