### ISSUE TITLE
std function causes redefinition error while linking

### ISSUE THREAD

**Issue by izsoandras** [DanielMartensson/CControl#4]
I am trying to use this library for my home project, on an ESP32 development board, within PlatformIO environment. The core of my program is written in C++, but I would like to use this library since it's pretty lighweight and is able to do what I need it to do.

But I have ran into a problem with linking: the "std" symbol is already existing in C++, as a namespace, so the compiler sees the declaration of your std function as a redefinition of that.

Are you aware of this and if so, is there a workaround, or am I doing something wrong?

**Comment by DanielMartensson** [comment]
> I am trying to use this library for my home project, on an ESP32 development board, within PlatformIO environment. The core of my program is written in C++, but I would like to use this library since it's pretty lighweight and is able to do what I need it to do.
> 
> But I have ran into a problem with linking: the "std" symbol is already existing in C++, as a namespace, so the compiler sees the declaration of your std function as a redefinition of that.
> 
> Are you aware of this and if so, is there a workaround, or am I doing something wrong?

Thank you for your message.
Yes! Se my latest update. Fixed now.
